FROM node:14-alpine as BUILD_IMAGE
WORKDIR /app
COPY package.json package-lock.json ./
# install dependencies
RUN npm ci
COPY . .
# build
RUN npm run build ./apps/posts
# remove dev dependencies

FROM node:14-alpine
WORKDIR /app
# copy from build image
COPY --from=BUILD_IMAGE /app/package.json ./package.json
COPY --from=BUILD_IMAGE /app/node_modules ./node_modules
COPY --from=BUILD_IMAGE /app/apps/posts/build ./.next
EXPOSE 3000
CMD ["npm", "start"]